module.exports = {
	users: [
		{
			_id: '0000d213816abba584714c0a',
			firstName: 'user',
			lastName: 'A',
			roles: [
				'0000d186816abba584714c97',
			],
			tag: 'teacher in course',
		},
		{
			_id: '0000d213816abba584714c0b',
			firstName: 'user',
			lastName: 'B',
			roles: [
				'0000d186816abba584714c96',
			],
			tag: 'student in course',
		},
		{
			_id: '0000d213816abba584714c0c',
			firstName: 'user',
			lastName: 'C',
			roles: [
				'0000d186816abba584714c96',
			],
			tag: 'student in course',
		},
		{
			_id: '0000d213816abba584714c0d',
			firstName: 'user',
			lastName: 'D',
			roles: [
				'0000d186816abba584714c97',
			],
			tag: 'subsitution teacher in course',
		},
		{
			_id: '0000d213816abba584714c0e',
			firstName: 'user',
			lastName: 'E',
			roles: [
				'0000d186816abba584714c96',
			],
			tag: 'student not in course',
		},
	],
	courses: [
		{
			_id: '59a3c657a2049554a93fec3a',
			name: 'Course A',
			teachersIds: [
				'0000d213816abba584714c0a',
			],
			userIds: [
				'0000d213816abba584714c0b', '0000d213816abba584714c0c',
			],
			substitutionIds: [

			],
			tag: 'course without substitution teacher',
		},
		{
			_id: '59a3c657a2049554a93fec3b',
			name: 'Course B',
			teachersIds: [
				'0000d213816abba584714c0a',
			],
			userIds: [
				'0000d213816abba584714c0b', '0000d213816abba584714c0c',
			],
			substitutionIds: [
				'0000d213816abba584714c0d',
			],
			tag: 'course with substitution teacher',
		},
	],
	roles: [
		{
			_id: '0000d186816abba584714c96',
			name: 'student',
			permissions: [
				'BASE_VIEW',
				'DASHBOARD_VIEW',
				'TOOL_VIEW',
				'PASSWORD_EDIT',
				'FOLDER_DELETE',
				'FOLDER_CREATE',
				'FILE_DELETE',
				'FILE_CREATE',
				'FILE_MOVE',
				'ACCOUNT_EDIT',
				'CALENDAR_VIEW',
				'CALENDAR_EDIT',
				'CALENDAR_CREATE',
				'FEDERALSTATE_VIEW',
				'HELPDESK_CREATE',
				'TOPIC_VIEW',
				'LINK_CREATE',
				'TOOL_VIEW',
				'NEWS_VIEW',
				'NOTIFICATION_VIEW',
				'NOTIFICATION_EDIT',
				'NOTIFICATION_CREATE',
				'PWRECOVERY_VIEW',
				'PWRECOVERY_EDIT',
				'PWRECOVERY_CREATE',
				'RELEASES_VIEW',
				'ROLE_VIEW',
				'USERGROUP_VIEW',
				'COURSEGROUP_CREATE',
				'COURSEGROUP_EDIT',
				'SYSTEM_VIEW',
				'USER_VIEW',
				'USER_EDIT',
				'HOMEWORK_VIEW',
				'COMMENTS_VIEW',
				'COMMENTS_CREATE',
				'COMMENTS_EDIT',
				'SUBMISSIONS_VIEW',
				'SUBMISSIONS_CREATE',
				'SUBMISSIONS_EDIT',
				'FILESTORAGE_VIEW',
				'FILESTORAGE_EDIT',
				'FILESTORAGE_CREATE',
				'CONTENT_VIEW',
				'CONTENT_NON_OER_VIEW',
				'FILESTORAGE_REMOVE',
				'TEAM_VIEW',
				'TEAM_EDIT',
				'TEAM_CREATE',
			],
		},
		{
			_id: '0000d186816abba584714c97',
			name: 'teacher',
			permissions: [
				'BASE_VIEW',
				'DASHBOARD_VIEW',
				'TOOL_VIEW',
				'PASSWORD_EDIT',
				'FOLDER_DELETE',
				'FOLDER_CREATE',
				'FILE_DELETE',
				'FILE_CREATE',
				'FILE_MOVE',
				'ACCOUNT_EDIT',
				'CALENDAR_VIEW',
				'CALENDAR_EDIT',
				'CALENDAR_CREATE',
				'FEDERALSTATE_VIEW',
				'HELPDESK_CREATE',
				'TOPIC_VIEW',
				'LINK_CREATE',
				'TOOL_VIEW',
				'NEWS_VIEW',
				'NOTIFICATION_VIEW',
				'NOTIFICATION_EDIT',
				'NOTIFICATION_CREATE',
				'PWRECOVERY_VIEW',
				'PWRECOVERY_EDIT',
				'PWRECOVERY_CREATE',
				'RELEASES_VIEW',
				'ROLE_VIEW',
				'USERGROUP_VIEW',
				'COURSEGROUP_CREATE',
				'COURSEGROUP_EDIT',
				'SYSTEM_VIEW',
				'USER_VIEW',
				'USER_EDIT',
				'HOMEWORK_VIEW',
				'COMMENTS_VIEW',
				'COMMENTS_CREATE',
				'COMMENTS_EDIT',
				'SUBMISSIONS_VIEW',
				'SUBMISSIONS_CREATE',
				'SUBMISSIONS_EDIT',
				'FILESTORAGE_VIEW',
				'FILESTORAGE_EDIT',
				'FILESTORAGE_CREATE',
				'CONTENT_VIEW',
				'CONTENT_NON_OER_VIEW',
				'FILESTORAGE_REMOVE',
				'TEAM_VIEW',
				'TEAM_EDIT',
				'TEAM_CREATE',
				'ACCOUNT_CREATE',
				'COURSE_EDIT',
				'HOMEWORK_EDIT',
				'HOMEWORK_CREATE',
				'LESSONS_VIEW',
				'NEWS_CREATE',
				'NEWS_EDIT',
				'SCHOOL_NEWS_EDIT',
				'STUDENT_CREATE',
				'STUDENT_DELETE',
				'STUDENT_SKIP_REGISTRATION',
				'SUBMISSIONS_SCHOOL_VIEW',
				'TEACHER_CREATE',
				'TOOL_CREATE',
				'TOOL_EDIT',
				'TOOL_NEW_VIEW',
				'TOPIC_CREATE',
				'TOPIC_EDIT',
				'USER_CREATE',
				'USERGROUP_CREATE',
				'USERGROUP_EDIT',
				'TEAM_INVITE_EXTERNAL',
				'LESSONS_CREATE',
			],
		},
	],
};
