dist: xenial
language: node_js
node_js:
  - '10.16'
branches:
  only:
    - develop
    - master
    - /^(?i:release|hotfix).*$/

stages:
  - test
  - name: build
    if: type = push && (branch = master || branch = develop || branch ~= /^(?i:release|hotfix).*$/)
  - name: deploy
    if: type = push && (branch = master || branch = develop || branch ~= /^(?i:release|hotfix).*$/)

env:
  global:
    - TZ=Europe/Berlin
    - GIT_SHA=$( git rev-parse HEAD )
    - DOCKERTAG="$( echo $TRAVIS_BRANCH | tr -s '[:punct:]' '-' | tr -s '[:upper:]' '[:lower:]' )_v$( jq -r '.version' package.json )_$TRAVIS_COMMIT"

jobs:
  include:
    - stage: test
      name: test:mocha
      script: npm run test
      services:
        - mongodb
        - redis-server
      env:
        - REDIS_URI=redis://localhost:6379

    # Build Docker Images
    - stage: build
      name: build
      language: generic
      script: bash ./deploy/build.sh

    # Deploy
    - stage: deploy
      name: deploy
      language: generic
      script: bash ./deploy/deploy.sh

cache: npm
