dist: xenial
language: node_js
node_js:
  - '10.16'
branches:
  only:
    - development
    - master
    - /^greenkeeper/.*$/
    - /^(?i:release|hotfix).*$/
services:
  - mongodb
  - redis-server
stages:
  - test
env:
  - REDIS_URI=redis://localhost:6379
jobs:
  include:
    - stage: test
      name: test:mocha
      script: npm run test
      cache: npm
