dist: xenial
language: node_js
node_js:
  - '10.16'
branches:
  only:
    - develop
    - master
    - /^(?i:release|hotfix).*$/
services:
  - mongodb
  - redis-server

stages:
  - test
  - name: build
    if: type = push && (branch = master || branch = develop || branch ~= /^(?i:release|hotfix).*$/)
  - name: deploy
    if: type = push && (branch = master || branch = develop || branch ~= /^(?i:release|hotfix).*$/)

env:
  - REDIS_URI=redis://localhost:6379
jobs:
  include:
    - stage: test
      name: test:mocha
      script: npm run test
      cache: npm

    # Build Docker Images
    - stage: build
      name: build
      language: generic
      script: bash ./deploy/build.sh

    # Deploy
    - stage: deploy
      name: deploy
      language: generic
      script: bash ./deploy/deploy.sh
