version: "3.7"

# example compose file

services:
  editor-mongodb:
    image: mongo:4.2
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    ports:
      - 27017:27017
    volumes:
      - data-editor-mongodb:/data/db
    restart: unless-stopped

  redis:
    image: redis:5.0.3

  schulcloud-editor:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://editor-mongodb:27017/schulcloud-editor
      - PORT=4101
      - SERVER_API_URL=http://server:3030
      - TIMEOUT=30000
      - REDIS_URI=redis://redis:6379
      - REDIS_KEY=schulcloud-editor-sync
    ports:
      - 4101:4101
    depends_on:
        - editor-mongodb
        - redis
    restart: unless-stopped

volumes:
    data-editor-mongodb:
