const mongoose = require('mongoose');

const { addTypeString } = require('../../../global/util');

const { Schema } = mongoose;

const subGroupSchema = new Schema({
	users: [{ type: Schema.Types.ObjectId }],
	title: { type: String, default: '' },
//	note: { type: String, default: '' },
//	feedback: { type: String, default: '' },
});


const groupSchema = new Schema({
	context: { type: String, default: 'lesson', enum: ['course', 'lesson'] },
	modus: { type: String, default: 'standard', enum: ['standard', 'optIn'] },
	contextInfo: { type: Schema.Types.ObjectId, required: true }, // ref id from context for search
	users: [{ type: Schema.Types.ObjectId }],
	groups: [subGroupSchema],
	title: { type: String, default: '' },
//	note: { type: String, default: '' },
//	feedback: { type: String, default: '' },
	autogenerated: { type: Boolean, default: false },
	deletedAt: { type: Date, expires: (60 * 60 * 24 * 30) },
	createdBy: { type: Schema.Types.ObjectId },
	updatedBy: { type: Schema.Types.ObjectId },
}, {
	timestamps: true,
});

groupSchema
	.post('find', addTypeString('group'))
	.post('findOne', addTypeString('group'));

module.exports = {
	GroupModel: mongoose.model('group', groupSchema),
};
